services:
    node:
        build: 
            context: .
            target: acid_node
        volumes:
            - .:/home/docker
        depends_on:
            - db

    db:
        build:
            context: .
            target: acid_postgres
        ports:
            - "8084:5432"
        environment:
            POSTGRES_PASSWORD: acid
            POSTGRES_USER: acid
            POSTGRES_DB: acid
        volumes:
            - acidDB:/var/lib/postgresql/data
    
volumes:
    acidDB: {}
    acid: {}